mealcost/cupboard/urls.py
from django.urls import path

from . import views

app_name = 'cupboard'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('create/', views.AddItemView.as_view(), name='add_item'),
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('delete/<int:pk>', views.ItemDelete.as_view(), name="delete_item")
]

mealcost/mealcost/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('cupboard/', include('cupboard.urls')),
    path('recipes/', include('recipe.urls')),
    path('admin/', admin.site.urls),
    path('about', views.about, name="about"),
    path('', views.index, name='index'),
]

mealcost/recipe/urls.py
from django.urls import path

from . import views

app_name = 'recipe'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.add_recipe, name='add_recipe'),
    path('createfromurl/', views.add_recipe_from_url, name='add_recipe_from_url'),
    # path('create/submit', views.add_recipe_form, name='add_recipe_form'),
    path('detail/<int:pk>', views.DetailView.as_view(), name='detail'),
    path('delete/<int:pk>', views.RecipeDelete.as_view(), name='delete_recipe'),
]

mealcost/cupboard/models.py
from django.db import models

class Item(models.Model):
    DAIRY = "DAIRY"
    FRUIT = "FRUIT"
    GRAIN = "GRAIN"
    MEAT = "MEAT"
    FROZEN = "FROZEN"
    VEGETABLE = "VEGETABLE"
    OTHER = "OTHER"

    CATEGORY_CHOICES = [
        (DAIRY, "Dairy"),
        (FRUIT, "Fruit"),
        (GRAIN, "Grain"),
        (MEAT, "Meat"),
        (FROZEN, "Frozen"),
        (VEGETABLE, "Vegetable"),
        (OTHER, "Other"),
    ]

    item_name = models.CharField(max_length=100, unique=True)
    price_per_cup = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    price_per_kg = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    price_per_unit = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    category = models.CharField(max_length=10, choices=CATEGORY_CHOICES, default=OTHER)

    def __str__(self):
        return '{}: ${:0.2f}/Cup'.format(self.item_name or "NONE", self.price_per_cup or 0.00)

mealcost/cupboard/forms.py
from django import forms
from .models import Item

from bootstrap_modal_forms.forms import BSModalForm

class AddItemForm(BSModalForm):
    class Meta:
        model = Item
        fields = '__all__'

mealcost/cupboard/views.py
"""
Django views defined for the cupboard application.
"""

from collections import defaultdict

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, DeleteView

from .forms import AddItemForm
from .models import Item

from bootstrap_modal_forms.generic import BSModalCreateView

class Index(ListView):
    """View defined for Cupboard index page.
    """
    model = Item
    template_name = 'cupboard/index.html'

    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        context['categories'] = [x[1] for x in Item.CATEGORY_CHOICES]  # Get list of all categories
        return context

class DetailView(DetailView):
    """View defined for the Cupboard detail page. 
    """
    model = Item
    template_name = 'cupboard/item_detail.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['recipes'] = [r for r in self.object.is_in.all()]
        return context

class AddItemView(BSModalCreateView):
    template_name = "cupboard/add_item.html"
    form_class = AddItemForm
    success_url = reverse_lazy("cupboard:index")

class ItemDelete(DeleteView):
    model = Item
    success_url = reverse_lazy('cupboard:index')

mealcost/cupboard/templates/cupboard/add_item.html
{% load crispy_forms_tags %}
<form action="" method="POST">
  {% csrf_token %}
  <div class="modal-header">
    <h5 class="modal-header">Add New Item</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    {{ form|crispy }}
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <input type="submit" value="Submit">
  </div>
</form>

mealcost/cupboard/templates/cupboard/header.html
<!doctype html>
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'site/style.css' %}" />
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

<div class="container">
<header class="main-header py-3 mb-2">
    <div class="row align-items-center">
        <div class="col-4 pt-1">
            <a class="text-muted" href="{% url 'about' %}">About</a>
        </div>
        <div class="col-4 text-center">
            <a class="main-header-logo text-dark" href={% url 'index' %}>Mealcost</a>
        </div>
        <div class="col-3 d-flex justify-content-end align-items-center">
            <a class="text-muted" href="{% url 'cupboard:index' %}">Cupboard</a>
        </div>
        <div class="col-1 d-flex justify-content-end align-items-center">
            <a class="text-muted" href="{% url 'recipe:index' %}">Recipes</a>
        </div>
    </div>
</header>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>

mealcost/cupboard/templates/cupboard/index.html
{% load static %}
{% load custom_template_tags %}

<head>
<link rel="stylesheet" type="text/css" href="{% static 'site/style.css' %}" />
</head>

<body>
    {% include "cupboard/header.html" %}
    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content"></div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="jumbotron">
                    <h1 class="display-4">Cupboard</h1>
                    <button id="create-item" class="btn btn-primary btn-lg" type="button" name='button'>Add new item</button>
                </div>
            </div>
        </div>
        {% if categories %}
            {% for category in categories %}
                {% get_category category as items_in_category %}
                <ul class="cursor-pointer list-group">
                    <li class="expand-items list-group-item active">{{ category|title }}</li>
                    <div class="hide=me">
                        {% for item in  items_in_category %}
                            <li class="list-group-item">
                                <a href="{% url 'cupboard:detail' item.id %}" class="item_list">{{ item.item_name }}</a>
                                <a href="{% url 'cupboard:delete_item' item.id %}">
                                    <span class="fa fa-trash" aria-hidden="true"></span>
                                </a>
                            </li>
                        {% endfor %}
                    </div>
                </ul>
            {% endfor %}
        {% else %}
            <p>You do not have any items in your cupboard.</p>
        {% endif %}
    <div>
</body>

<script type="text/javascript">
$(function() {
    $("#create-item").modalForm({
        formURL: "{% url 'cupboard:add_item' %}"
    });
});

$(".expand-items").click(function () {

    $content = $(this).next();
    $content.slideToggle(500)
});

</script>

mealcost/cupboard/templates/cupboard/item_confirm_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete item "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

mealcost/cupboard/templates/cupboard/item_detail.html
<html lang="en">
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'site/style.css' %}" />
</head>
<body>
    {% include "cupboard/header.html" %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="jumbotron">
                    <h1 class="display-4">{{ item.item_name }}</h1>
                    <ul class="list-group">
                        {% if item.price_per_cup %}
                            <li class="list-group-item">${{ item.price_per_cup }}/Cup</li>
                        {% endif %}
                        {% if item.price_per_kg %}
                            <li class="list-group-item">${{ item.price_per_kg }}/Kg</li>
                        {% endif %}
                        {% if item.price_per_unit %}
                            <li class="list-group-item">${{ item.price_per_unit }}/Unit</li>
                        {% endif %}
                    </ul>
                    {% if recipes %}
                        <h2>Is ingredient in: </h2>
                        <ul class="list-group">
                            {% for r in recipes %}
                                <li class="list-group-item"><a href="{% url 'recipe:detail' r.id %}" class="item_list">{{ r.recipe_name }}</a></li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p>This item is not a part of any saved recipes.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</body>
</html>