mealcost/mealcost/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('cupboard/', include('cupboard.urls')),
    path('recipes/', include('recipe.urls')),
    path('admin/', admin.site.urls),
    path('about', views.about, name="about"),
    path('', views.index, name='index'),
]

mealcost/recipe/urls.py
from django.urls import path

from . import views

app_name = 'recipe'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.add_recipe, name='add_recipe'),
    path('createfromurl/', views.add_recipe_from_url, name='add_recipe_from_url'),
    # path('create/submit', views.add_recipe_form, name='add_recipe_form'),
    path('detail/<int:pk>', views.DetailView.as_view(), name='detail'),
    path('delete/<int:pk>', views.RecipeDelete.as_view(), name='delete_recipe'),
]

mealcost/recipe/models.py
from django.db import models

from cupboard.models import Item

class ItemRecipeJunction(models.Model):
    recipe = models.ForeignKey('recipe.Recipe', on_delete=models.CASCADE)
    item = models.ForeignKey('cupboard.Item', on_delete=models.CASCADE)    
    cups_of_item = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    kgs_of_item = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    units_of_item = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return f'{self.item.item_name} is in {self.recipe.recipe_name}'


class Recipe(models.Model):
    recipe_name = models.CharField(max_length=100, unique=True)
    ingredients = models.ManyToManyField(Item, through=ItemRecipeJunction, related_name="is_in")

    def __str__(self):
        return f'{self.recipe_name}'

mealcost/recipe/forms.py
from django import forms
from django.forms.widgets import CheckboxSelectMultiple, RadioSelect

from recipe.models import ItemRecipeJunction

from .models import Recipe


class AddRecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['recipe_name']

mealcost/recipe/views.py
from collections import defaultdict

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DeleteView, DetailView

from cupboard.models import Item
from recipe.forms import AddRecipeForm
from recipe.models import ItemRecipeJunction
from recipe.parse_recipes import parse_recipe_url
from recipe.constants import KNOWN_UNITS

from .models import Recipe


# Create your views here.
class IndexView(ListView):
    """View defined for Recipe index page.
    """
    model = Recipe
    context_object_name = 'recipes'
    template_name = 'recipe/index.html'


class RecipeDelete(DeleteView):
    model = Recipe
    success_url = reverse_lazy('recipe:index')


class DetailView(DetailView):
    """View defined for the Recipe detail page. 
    """
    model = Recipe
    template_name = 'recipe/recipe_detail.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['recipe'] = self.object
        recipe = self.object

        ingredients = {}
        price = 0.0
        for i in recipe.ingredients.all():
            print("i = {}".format(i))
            # Get all ingredients in the current recipe
            j = ItemRecipeJunction.objects.get(recipe=recipe, item=i)
            print('j = {}'.format(j))

            if j.cups_of_item and i.price_per_cup:
                price += (float(j.cups_of_item) * float(i.price_per_cup))
                ingredients[i] = ('Cup', j.cups_of_item)
            elif j.kgs_of_item and i.price_per_kg:
                price += (float(j.kgs_of_item) * float(i.price_per_kg))
                ingredients[i] = ('Kg', j.kgs_of_item)
            elif j.units_of_item and i.price_per_unit:
                price += (float(j.units_of_item) * float(i.price_per_unit))
                ingredients[i] = ('Unit', j.units_of_item)
            else:
                units_specified = "Cup" if j.cups_of_item else ("Kg" if j.kgs_of_item else ("Unit" if j.units_of_item else ""))
                prices_specified = i.price_per_cup or i.price_per_kg or i.price_per_unit or 0.0
                print("units = {}, price = {}".format(units_specified, prices_specified))
                ingredients[i] = (units_specified, prices_specified)
#                context['price_error'] = "Could not calculate price of recipe because youve only specified {} for item amount and only {} for price".format(units_specified, prices_specified)
        context['ingredients'] = ingredients
        context['price'] = '{:.2f}'.format(price)
        return context

def add_recipe(request):
    def save_to_database(request, name):
        """Given a request and a recipe name add the new recipe to our database

        Args:
            request (HttpRequest): Contains our ingredient information
            name (str): name of our new recipe
        """
        new_recipe = Recipe(recipe_name=name)
        new_recipe.save()

        # Create a new ItemRecipeJunction based on each ingredient we have in our recipe
        ingredients = Item.objects.all()
        for ingredient in ingredients:
            name = ingredient.item_name
            amount = request.POST[f"{name}_amount"].strip()
            if not amount:
                continue
            measurement = request.POST[f"{name}_measurement"]
            ingredient = Item.objects.get(item_name=name)
            if measurement == "cups":
                new_junction = ItemRecipeJunction(recipe=new_recipe, item=ingredient, cups_of_item=amount)
            elif measurement == "kgs":
                new_junction = ItemRecipeJunction(recipe=new_recipe, item=ingredient, kgs_of_item=amount)
            elif measurement == "units":
                new_junction = ItemRecipeJunction(recipe=new_recipe, item=ingredient, units_of_item=amount)
            new_junction.save()

    if request.method == "POST":
        # We are processing our form data
        form = AddRecipeForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["recipe_name"]
            save_to_database(request, name)
            return HttpResponseRedirect(reverse('recipe:index'), {'recipe': Recipe.objects.all()})
    else:
        form  = AddRecipeForm()
        return render(request, 'recipe/add_recipe.html', context={"form": form, "ingredients": Item.objects.all()})

def add_recipe_from_url(request):
    def save_to_database_from_url(request, name):
        """Given a request and a recipe name add the new recipe to our database

        Args:
            request (HttpRequest): Contains our URL
            name (str): name of our new recipe
        """
        new_recipe = Recipe(recipe_name=name)
        new_recipe.save()

        ingredient_list = parse_recipe_url(request.POST['url-input'])
        print('\n'.join(ingredient_list))
        for ingredient in ingredient_list:
            amount = ingredient.split()[0]
            if not amount.isnumeric():
                item_name = ingredient
                amount = 1
            else:
                unit = ingredient.split()[1]
                if unit in KNOWN_UNITS:
                    item_name = ' '.join(ingredient.split()[2:])
                else:
                    item_name = ' '.join(ingredient.split()[1:])
            try:
                item = Item.objects.get(item_name=item_name)
            except Item.DoesNotExist:
                item = Item(item_name=item_name, price_per_cup=0, price_per_kg=0, price_per_unit=0, category=Item.OTHER)
                item.save()
            if unit in ('cup', 'cups'):
                new_junction = ItemRecipeJunction(recipe=new_recipe, item=item, cups_of_item=amount)
            elif unit in ('tbsp', 'tablespoon', 'tablespoons'):
                new_junction = ItemRecipeJunction(recipe=new_recipe, item=item, cups_of_item=round(float(amount)/16.0, 2))
            elif unit in ('tsp', 'teaspoon', 'teaspoons'):
                new_junction = ItemRecipeJunction(recipe=new_recipe, item=item, cups_of_item=round(float(amount)/48.0, 2))
            elif unit in ('kgs', 'kg'):
                new_junction = ItemRecipeJunction(recipe=new_recipe, item=item, kgs_of_item=amount)
            elif unit in ('g', 'gram', 'grams'):
                new_junction = ItemRecipeJunction(recipe=new_recipe, item=item, kgs_of_item=round(float(amount)*1000, 2))
            elif unit in ('lbs', 'pound', 'pounds'):
                new_junction = ItemRecipeJunction(recipe=new_recipe, item=item, kgs_of_item=round(float(amount)*2.2, 2))
            elif unit not in KNOWN_UNITS:
                print("NOT RECOGNIZING unit {} so just treating item {} as a unit".format(unit, item))
                new_junction = ItemRecipeJunction(recipe=new_recipe, item=item, units_of_item=amount)
            else:
                print("Something went wrong with ingredient {}. Got amount {}, unit {}, item {}".format(ingredient, amount, unit, item))
                continue
            new_junction.save()

    if request.method == "POST":
        # We are processing our form data
        form = AddRecipeForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["recipe_name"]
            save_to_database_from_url(request, name)
            return HttpResponseRedirect(reverse('recipe:index'), {'recipe': Recipe.objects.all()})
    else:
        form  = AddRecipeForm()
        return render(request, 'recipe/add_recipe_from_url.html', context={"form": form})

mealcost/recipe/templates/recipe/add_recipe.html
<form action="" method="POST">
  {% csrf_token %}
  <div class="modal-header">
    <h5 class="modal-header">Add new recipe</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    {{ form }}
    <br>
    <br>

    {% for ingredient in ingredients %}
      <label for="{{ ingredient.item_name }}_cups">{{ ingredient.item_name }}: </label>
      <input type="text" placeholder="amount" id="{{ ingredient.item_name }}_amount" name="{{ ingredient.item_name }}_amount" pattern="[0-9]+(.[0-9]+)?">
      <select id="{{ ingredient.item_name }}_measurement" name="{{ ingredient.item_name }}_measurement">
        <option value="cups">Cups</option>
        <option value="kgs">Kgs</option>
        <option value="units">Units</option>
      </select>
      <br>
      <br>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <input type="submit" value="Submit">
  </div>
</form>

mealcost/recipe/templates/recipe/add_recipe_from_url.html
<form action="" method="POST">
  {% csrf_token %}
  <div class="modal-header">
    <h5 class="modal-header">Add new recipe</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    {{ form }}
    <br>
    <br>

    <label for="url-input">URL:  </label>
    <input type="text" placeholder="https://url.com/recipename" id="url-input" name="url-input">
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <input type="submit" value="Submit">
  </div>
</form>

mealcost/recipe/templates/recipe/index.html
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'site/style.css' %}" />
</head>

<body>
    {% include "cupboard/header.html" %}
    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content"></div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="jumbotron">
                    <h1 class="display-4">Recipes</h1>
                    <button id="create-recipe" class="btn btn-primary btn-lg" role="button">Add new recipe</button>
                    <button id="create-recipe-from-url" class="btn btn-primary btn-lg" role="button">Add new recipe from URL</button>
                </div>
            </div>
        </div>
    
        {% if recipes %}
            <ul class="list-group">
                {% for recipe in recipes %}
                    <li class="list-group-item">
                        <a href="{% url 'recipe:detail' recipe.id %}">{{ recipe.recipe_name }}</a>
                        <a href="{% url 'recipe:delete_recipe' recipe.id %}">
                            <span class="fa fa-trash" aria-hidden="true"></span>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>You do not have any saved recipes.</p>
        {% endif %}
    <div>
</body>

<script type="text/javascript">
$(function() {
    $("#create-recipe").modalForm({
        formURL: "{% url 'recipe:add_recipe' %}"
    });
});
$(function() {
    $("#create-recipe-from-url").modalForm({
        formURL: "{% url 'recipe:add_recipe_from_url' %}"
    });
});
</script>

mealcost/recipe/templates/recipe/recipe_confirm_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete recipe "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

mealcost/recipe/templates/recipe/recipe_detail.html
<html lang="en">
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'site/style.css' %}" />
</head>

<body>
    {% include "cupboard/header.html" %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="jumbotron">
                    <h1 class="display-4">{{ recipe.recipe_name }}</h1>
                    {% if ingredients %}
                        <ul class="list-group">
                            {% for ingredient, value in ingredients.items %}
                                {% if value.0 == "Cup" %}
                                    <li class="list-group-item">{{ ingredient.item_name }} (${{ ingredient.price_per_cup }}/{{ value.0 }}): 
                                        {{ value.0 }}s: {{ value.1 }}
                                    </li>
                                {% elif value.0 == "Kg" %}
                                    <li class="list-group-item">{{ ingredient.item_name }} (${{ ingredient.price_per_kg }}/{{ value.0 }}): 
                                        {{ value.0 }}s: {{ value.1 }}
                                    </li>
                                {% elif value.0 == "Unit" %}
                                    <li class="list-group-item">{{ ingredient.item_name }} (${{ ingredient.price_per_unit }}/{{ value.0 }}): 
                                        {{ value.0 }}s: {{ value.1 }}
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p>This recipe has no ingredients</p>
                    {% endif %}
                    {% if price %}
                        <h5>Total price of recipe: ${{ price }}</h5>
                    {% elif price_error %}
                        {{ price_error }}
                    {% endif %}
            </div>
        </div>
    </div>
</body>
</html>